name: Compile TWRP
on:
  push:
    branches: [ 'android-7.1' ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-18.04
    env:
      USE_CCACHE: "1"
      CCACHE_EXEC: "/usr/bin/ccache"
    steps:
      - name: Configure
        run: |
          curl https://storage.googleapis.com/git-repo-downloads/repo | sudo tee /usr/bin/repo > /dev/null
          sudo chmod +x /usr/bin/repo
          sudo apt install -yq bc bison build-essential ccache curl flex g++-multilib gcc-multilib git gnupg gperf imagemagick lib32ncurses5-dev lib32readline-dev lib32z1-dev liblz4-tool libncurses5 libncurses5-dev libsdl1.2-dev libssl-dev libxml2 libxml2-utils lzop pngcrush rsync schedtool squashfs-tools xsltproc zip zlib1g-dev libwxgtk3.0-dev python3
          sudo ln -sf /usr/bin/python3 /usr/bin/python
          git config --global user.email "1156393759@qq.com"
          git config --global user.name "gamecss@bot"
      - name: Get source
        run: |
          mkdir $GITHUB_WORKSPACE/twrp
          cd $GITHUB_WORKSPACE/twrp
          repo init --depth=1 -u https://github.com/minimal-manifest-twrp/platform_manifest_twrp_omni.git -b twrp-7.1
          repo sync -c -f --no-tags --no-clone-bundle -j16
          rm -rf bootable/recovery && git clone https://github.com/TeamWin/android_bootable_recovery -b android-9.0 --depth 1 bootable/recovery
      - name: Setup device
        uses: actions/checkout@v3
        with:
          path: 'twrp/device/Xiaoxun/MiKidsWatch_F3'   
      - name: Build
        run: |
          cd $GITHUB_WORKSPACE/twrp
          source build/envsetup.sh
          croot
          lunch omni_MiKidsWatch_F3-eng
          mka -j$(nproc --all) recoveryimage
